apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonelli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bonelli
  template:
    metadata:
      labels:
        app: bonelli
    spec:
      containers:
      - name: bonelli
        image: devync/bonelli:latest
        ports:
        - containerPort: 80
