apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cyphers-dev-cert
spec:
  dnsNames:
    - cyphers.dev
  secretName: cyphers-dev-cert
  issuerRef:
    name: digitalocean-issuer
    kind: ClusterIssuer
